### ISSUE TITLE
Version tagging

### ISSUE THREAD

**Issue by smitj** [channelengine/api-client-php#2]
Please consider using tags when distributing this library. This allows for more granular version control and an easier process of managing a changelog.

Right now users are basically forced to set the checkout to a specific hash in order to prevent pulling in (un)intentional BC-breaking changes. Although "it works"™, it's not a preferred method.

**Comment by christiaanderidder** [comment]
We have added tagged versions to our repository.
Beware that the package name has been renamed to api-client-php to match the repository:
https://packagist.org/packages/channelengine/api-client-php
